# Generated by Django 6.0 on 2026-02-24 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB', 'Lab Personnel')], max_length=10),
        ),
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('lab_department', models.CharField(blank=True, choices=[('HEMATOLOGY', 'Hematology'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology & Imaging'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('qualification', models.CharField(blank=True, default='', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default='True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LAb Profile',
                'verbose_name_plural': 'LAb Profiles',
            },
        ),
    ]
