# Generated by Django 6.0 on 2026-02-10 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_relation', models.CharField(max_length=100)),
                ('allergies', models.TextField(blank=True, help_text='List any known allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='List any chronic conditions')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chief_complaint', models.TextField(help_text='Main reaso for visit')),
                ('present_illness', models.TextField(help_text='History of preset illness')),
                ('past_medical_history', models.TextField(blank=True, help_text='Relevant past medical history')),
                ('family_history', models.TextField(blank=True, help_text='Relevant family medical history')),
                ('social_history', models.TextField(blank=True, help_text='Lifestyle factors, occupation, etc.')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='In Farenheit', max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g., 120/80', max_length=20)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='In kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='In cm', max_digits=5, null=True)),
                ('physical_examination', models.TextField(blank=True, help_text='Physical examination findings')),
                ('doctor_notes', models.TextField(blank=True, help_text='Additional notes by the doctor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories_recorded', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='records.patient')),
            ],
            options={
                'verbose_name': 'Medical History',
                'verbose_name_plural': 'Medical Histories',
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField()),
                ('condition', models.CharField(help_text='Name of the condition/disease', max_length=200)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=20)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('CHRONIC', 'Chronic'), ('UNDER_OBSERVATION', 'Under Observation')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of diagnosis')),
                ('symptoms', models.TextField(blank=True, help_text='List of symptoms')),
                ('test_results', models.TextField(blank=True, help_text='Relevant test results')),
                ('treatment_plan', models.TextField(blank=True, help_text='Recommended treatment plan')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('medical_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.medicalhistory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.patient')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosis_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField()),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once Daily'), ('TWICE_DAILY', 'Twice Daily'), ('THREE_TIMES_DAILY', 'Three Times Daily'), ('FOUR_TIMES_DAILY', 'Four Times Daily'), ('EVERY_4_HOURS', 'Every 4 Hours'), ('EVERY_6_HOURS', 'Every 6 Hours'), ('EVERY_8_HOURS', 'Every 8 Hours'), ('EVERY_12_HOURS', 'Every 12 Hours'), ('AS_NEEDED', 'As Needed'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=30)),
                ('route', models.CharField(help_text='e.g., Oral, Intravenous, Topical', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks, 1 month', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, help_text='Total quantity to be dispensed', max_length=50)),
                ('refills', models.IntegerField(default=0, help_text='Number of refills allowed')),
                ('instructions', models.TextField(help_text='Detailed instructions for patient')),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions or warnings')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='records.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date', '-created_at'],
            },
        ),
    ]
