# Generated by Django 6.0 on 2026-02-24 21:17

import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Medical History', 'verbose_name_plural': 'Medical Histories'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='chief_complaint',
            field=models.TextField(help_text='Main reason for visit'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField()),
                ('result_summary', models.TextField(help_text='Summary of text results')),
                ('lab_notes', models.TextField(blank=True, help_text='Lab Personnel observations and technical notes')),
                ('scan_notes', models.TextField(blank=True, help_text='Specific notes for imaging/scans (body part, technique, contrast used, etc.)')),
                ('is_abnormal', models.BooleanField(default=False, help_text='Flag f results are abnormal')),
                ('interpretation', models.TextField(blank=True, help_text="Doctor's interprettation and clinical notes")),
                ('interpreted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interpretated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_interpreted', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='LabResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=records.models.lab_result_file_path, validators=[records.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Report'), ('IMAGE', 'Image (JPG, PNG)'), ('scan', 'Medical Scan (DICOM / High-res image)'), ('OTHER', 'Other')], max_length=10)),
                ('file_name', models.CharField(blank=True, help_text='Descriptive file for the file', max_length=250)),
                ('description', models.CharField(blank=True, help_text='Brief description for this file', max_length=500)),
                ('file_notes', models.TextField(blank=True, help_text='Specific observation or notes about this file/scan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='records.labresult')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Result File',
                'verbose_name_plural': 'Lab Result Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BLOOD', 'Blood'), ('IMAGING', 'Imaging (X-Ray, CT, MRI, Ultrasound)'), ('URINE', 'Urine Test'), ('CARDIAC', 'Cardiac (ECG, Echo)'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other / Custom')], max_length=20)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT (Immediate)')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed by Doctor'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=15)),
                ('instructions', models.TextField(blank=True, help_text='Instruction for the lab personnel')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Lab Personnel who picked up this test', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='records.diagnosis')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_ordered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='records.patient')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='records.labtest'),
        ),
    ]
